server:
  port: 8081
spring:
  application:
    name: apitest
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER
springfox:
  documentation:
    swagger:
      v2:
        path: /swagger.json